wordtools_data:
  image: sendmarsh/wordtools_data
  container_name: wordtools_data
  ports:
     - "3306:3306"
  environment:
     - MYSQL_ROOT_PASSWORD
     - MYSQL_PASSWORD
wordtools_api:
  image: sendmarsh/wordtools_api
  container_name: wordtools_api
  ports:
     - "8081:8081"
  environment:
     - MYSQL_PASSWORD
  links:
     - wordtools_data:wordtools-data
wordtools_presentation:
  image: sendmarsh/wordtools_presentation
  container_name: wordtools_presentation
  ports:
     - "8080:8080"
  links:
     - wordtools_api:wordtools-api