wordtools-data:
  image: sendmarsh/wordtools-data
  container_name: wordtools-data
  ports:
     - "3306:3306"
  environment:
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_ROOT_PASSWORD
     - MYSQL_PASSWORD
wordtools-api:
  image: sendmarsh/wordtools-api
  container_name: wordtools-api
  ports:
     - "8081:8081"
  environment:
     - MYSQL_USER
     - MYSQL_PASSWORD
  links:
     - wordtools-data:wordtools-data
wordtools-presentation:
  image: sendmarsh/wordtools-presentation
  container_name: wordtools-presentation
  ports:
     - "8080:8080"
  links:
     - wordtools-api:wordtools-api